apiVersion: apps/v1
kind: Deployment
metadata:
  name: tektondemo-app
  labels:
    app: tektondemo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tektondemo-app
  template:
    metadata:
      labels:
        app: tektondemo-app
    spec:
      containers:
      - name: webserver
        # Hier kijkt hij in het project 'tektondemo' naar jouw gebouwde image
        image: image: image-registry.openshift-image-registry.svc:5000/demotekton/tektondemo-git:latest
        ports:
        - containerPort: 8080
